#   create a secret (an authentication token) for the "sample" service account
apiVersion: v1
kind: Secret
metadata:
  name: sample-token
  namespace: sample
  annotations:
    kubernetes.io/service-account.name: sample
type: kubernetes.io/service-account-token
